### ISSUE TITLE
ENH: Emulating pct_change behaviour in terms of fractional difference on dataframes or series

### ISSUE THREAD

**Issue by CarloNicolini** [simaki/fracdiff#64]
I dont' understand how to compute a `pct_change()` in terms of fracdiff.

In pandas the `pct_change()` on a Series is computed as `( x(t) - x(t-1) )/ x(t-1)`, where the backward difference operator is at the numerator.
Emulating this function with a fractional difference approach in mind requires to take the fractional difference at the numerator at some order, but I cannot figure out what to put at the denominator. Does it make sense to simply use `x(t-1)`? Wouldn't this imply using order 1 shift operator at the denominator?

**Comment by simaki** [comment]
I think that makes sense, but let me suggest alternatives as well.

**1. Use proper weighted average**

Fracdiff is defined using backshift operator `d` as follows:

```txt
(1 - d)^n = 1 - (c_1 d + c_2 d^2 + ...)
```

We can check that the coefficients are positive and add up to unity, i.e. `c_k > 0` and `\sum_k c_k = 1`.
So the fracdiff can be interpreted as the difference between `x(t)` and the weighted average of the preceding observations `c_1 x(t-1) + c_2 x(t-2) + ...`.

With this in my mind, one extension would be `pct_change = fracdiff(x) / (c_1 x(t-1) + c_2 x(t-2) + ...)`.

**2. Use log return**

Log return `log_return(x) = log(x(t) / x(t-1))` is similar to `pct_change`.
If you are willing to use it instead of `pct_change` it resolves the ambiguity of the denominator, because `pct_change(x) = diff(log(x))` has a natural extension to fracdiff, `fracdiff(log(x))`.

**Comment by simaki** [comment]
closing until further updates.
